FROM golang
LABEL maintainer="routedworld@gmail.com"
WORKDIR /workspace
RUN apt-get update && apt-get install -y --no-install-recommends \
        tini=* \
     && rm -fr /var/lib/apt/lists/*
COPY go.mod ./
RUN go mod download -json
COPY main.go ./
RUN go install
ENTRYPOINT ["tini", "-g", "--", "sh", "-c", "helloGo \"${0} ${*}\""]
CMD ["Marcia"]